name: PR Deployment Previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  deploy-preview:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm i -g pnpm && pnpm install

      - name: Build
        run: pnpm build

      - name: Deploy Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./dist
